CREATE TABLE IF NOT EXISTS accounts (
  id UUID PRIMARY KEY,
  balance BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
  id UUID PRIMARY KEY,
  account_id UUID NOT NULL,
  amount BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE UNLOGGED TABLE IF NOT EXISTS staging_0 (LIKE transactions INCLUDING ALL);
CREATE UNLOGGED TABLE IF NOT EXISTS staging_1 (LIKE transactions INCLUDING ALL);
