// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/transaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       []byte                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TransactionType int32                  `protobuf:"varint,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_api_proto_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CreateTransactionRequest) GetTransactionType() int32 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransactionBatch struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transactions  []*CreateTransactionRequest `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_api_proto_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionBatch) GetTransactions() []*CreateTransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_api_proto_v1_transaction_proto protoreflect.FileDescriptor

const file_api_proto_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/transaction.proto\x12\x03api\"|\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\fR\taccountId\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\x05R\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"U\n" +
	"\x10TransactionBatch\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.api.CreateTransactionRequestR\ftransactionsB6Z4github.com/alexmcook/transaction-ledger/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_transaction_proto_rawDescOnce sync.Once
	file_api_proto_v1_transaction_proto_rawDescData []byte
)

func file_api_proto_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_proto_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_transaction_proto_rawDesc), len(file_api_proto_v1_transaction_proto_rawDesc)))
	})
	return file_api_proto_v1_transaction_proto_rawDescData
}

var file_api_proto_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil), // 0: api.CreateTransactionRequest
	(*TransactionBatch)(nil),         // 1: api.TransactionBatch
}
var file_api_proto_v1_transaction_proto_depIdxs = []int32{
	0, // 0: api.TransactionBatch.transactions:type_name -> api.CreateTransactionRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_transaction_proto_init() }
func file_api_proto_v1_transaction_proto_init() {
	if File_api_proto_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_transaction_proto_rawDesc), len(file_api_proto_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_transaction_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_proto_v1_transaction_proto = out.File
	file_api_proto_v1_transaction_proto_goTypes = nil
	file_api_proto_v1_transaction_proto_depIdxs = nil
}
