// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/accounts":{"post":{"description":"Creates a new account for a user","produces":["text/plain"],"summary":"Create a new account","responses":{"201":{"description":"Account created with ID","schema":{"type":"string"}},"500":{"description":"Failed to create account","schema":{"type":"string"}}}}},"/health":{"get":{"description":"Returns 200 OK if the API is running","produces":["text/plain"],"summary":"API Health check","responses":{"200":{"description":"OK","schema":{"type":"string"}}}}},"/users":{"post":{"description":"Creates a new user in the system","produces":["text/plain"],"summary":"Create a new user","responses":{"201":{"description":"User created with ID","schema":{"type":"string"}},"500":{"description":"Failed to create user","schema":{"type":"string"}}}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Transaction Ledger API",
	Description:      "Transaction Ledger API for managing users and accounts",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
